//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        [DataType(DataType.Password)]
        public string User_Pass { get; set; }
        public int Type_ID { get; set; }
        public Nullable<int> Society_ID { get; set; }
    
        public virtual User_Type User_Type { get; set; }
        public virtual Society Society { get; set; }
    }
}
